### ISSUE TITLE
Layout Parameter

### ISSUE THREAD

**Issue by herochen11** [tud-ccc/RTSim#1]
Hi,

I want to ask how to change the layout to Serial mode? 

I read the paper about RTSim. In the paper, it mentioned that there is a Layout parameter 
can determine using Serial or Interleaved Layout.  But I didn't find any configuration parameter 
named Layout.

If I want to change the layout to Serial, What modification should I do to change to Serial Layout?

Thanks you!

**Comment by asifuet** [comment]
> Hi,
> 
> I want to ask how to change the layout to Serial mode?
> 
> I read the paper about RTSim. In the paper, it mentioned that there is a Layout parameter
> can determine using Serial or Interleaved Layout. But I didn't find any configuration parameter
> named Layout.
> 
> If I want to change the layout to Serial, What modification should I do to change to Serial Layout?
> 
> Thanks you!

Hi, This is not explicitly maintained in this version for good reasons e.g., from the perspective of the shifts, this gives worst-case shifting and from the perspective of implementing the shift controller in hardware, this significantly increases the overhead of the head status array (each track needs to be maintained separately). However, in case you need it, I can look into the older version and make it accessible. 

-Asif

**Comment by herochen11** [comment]
> Hi, This is not explicitly maintained in this version for good reasons e.g., from the perspective of the shifts, this gives worst-case shifting and from the perspective of implementing the shift controller in hardware, this significantly increases the overhead of the head status array (each track needs to be maintained separately). However, in case you need it, I can look into the older version and make it accessible.
> 
> -Asif

Hi, thanks for your reply. I need the old version because my experiment require to run in serial mode. 
Thanks you very much!!

**Comment by asifuet** [comment]
> > Hi, This is not explicitly maintained in this version for good reasons e.g., from the perspective of the shifts, this gives worst-case shifting and from the perspective of implementing the shift controller in hardware, this significantly increases the overhead of the head status array (each track needs to be maintained separately). However, in case you need it, I can look into the older version and make it accessible.
> > -Asif
> 
> Hi, thanks for your reply. I need the old version because my experiment require to run in serial mode.
> Thanks you very much!!

Please pull the serial-layout branch. You should see the layout parameter in the config. Please be careful with the address mapping. As an example, I have added a sample 'test.nvt' trace to the Test traces folder and enabled printing a debug message showing different address parameters.

-Asif

**Comment by herochen11** [comment]
I am sorry for the late reply. Thank for the serial-layout branch.
